version: "3.2"
services:
  nginx:
    container_name: nginx
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - app1
      - app2
    networks:
      - load_balancer

  app1:
    container_name: App1
    image: "httpd:2.4"
    volumes:
      - ./app1/index.html:/usr/local/apache2/htdocs/index.html
      - ./app1/hello.png:/usr/local/apache2/htdocs/hello.png
    networks:
      - load_balancer
    
  app2:
    container_name: App2
    image: "httpd:2.4"
    volumes:
      - ./app2/index.html:/usr/local/apache2/htdocs/index.html
      - ./app2/hello.png:/usr/local/apache2/htdocs/hello.png
    networks:
      - load_balancer

networks:
  load_balancer:
    driver: bridge